"""Create users table

Revision ID: 497ea6d6247f
Revises: 
Create Date: 2025-08-14 14:59:36.096718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497ea6d6247f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('username', sa.String, unique=True, index=True, nullable=False),
        sa.Column('hashed_password', sa.String, nullable=False),
        sa.Column('role', sa.String, nullable=False)
    )
    op.create_table(
        'contacts',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('email', sa.String, nullable=True),
        sa.Column('phone', sa.String, nullable=True),
        sa.Column('address', sa.String, nullable=True)
    )
    op.create_table(
        'logs',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('method', sa.String, nullable=False),
        sa.Column('path', sa.String, nullable=False),
        sa.Column('query_params', sa.String, nullable=True),
        sa.Column('body', sa.String, nullable=True),
        sa.Column('timestamp', sa.String, nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('contacts')
    op.drop_table('users')
    # ### end Alembic commands ###
